apiVersion: apps/v1
kind: Deployment
metadata:
  name: examen-2026
  namespace: examen-26
spec:
  replicas: 5
  selector:
    matchLabels:
      app: examen-2026
  template:
    metadata:
      labels:
        app: examen-2026
    spec:
      containers:
        - name: examen-2026
          image: medhakimarbi/frontend:1.0.0
          ports:
            - containerPort: 80
