apiVersion: v1
kind: Service
metadata:
  name: examen-2026
  namespace: examen-26
spec:
  type: NodePort
  selector:
    app: examen-2026
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
